import type { Metadata } from "next";
import "./globals.css";

import { ReactNode } from "react";
import { cookies } from "next/headers";

import Providers from "../providers/LanguageProvider";
import { ThemeProvider } from "../providers/ThemeProvider";
import FontProvider from "../providers/FontProvider";

import Header from "./components/UI/Header";
import Footer from "./components/UI/Footer";
import MobileNavigationMenu from "./components/MobileUI/MobileNavigationMenu";
import BottomNav from "./components/MobileUI/BottomNav";
import { dm_sans, pt_sans } from "./utils/fontConfig";
import CurrencyProvider from "@/providers/CurrencyProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const nextCookies = await cookies();
  const localeFromCookie = nextCookies.get("NEXT_LOCALE")?.value || "en";

  let messages;
  try {
    messages = (await import(`../messages/${localeFromCookie}.json`)).default;
  } catch (error) {
    console.error(`Ошибка загрузки сообщений для локали ${localeFromCookie}:`, error);
    messages = (await import(`../messages/en.json`)).default;
  }

  // Определяем класс шрифта для локали
  const fontClassName =
    localeFromCookie === "ru" ? pt_sans.className : dm_sans.className;
    
  return (
    <html lang={localeFromCookie} className={fontClassName}>
      <body className="dark:bg-[url('/assets/background-dark.png')] bg-no-repeat bg-cover"
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <CurrencyProvider>
          <Providers initialLocale={localeFromCookie} initialMessages={messages}>
            <FontProvider
              fonts={{
                en: dm_sans.className,
                ru: pt_sans.className,
                default: dm_sans.className,
              }}
            >
              <Header />
              <MobileNavigationMenu />
              {children}
              <BottomNav />
              <Footer />
            </FontProvider>
          </Providers>
          </CurrencyProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
