name: Frontend CI/CD
on:
  push: 
    branches: [frontend_dev]

jobs:

  lint:
    defaults:
        run:
          working-directory: ./frontend

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: frontend_dev

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint
    
  build:
    defaults:
        run:
          working-directory: ./frontend

    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: frontend_dev
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build


  check-backend-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: frontend_dev
          fetch-depth: 0

      - name: Check for changes in backend
        run: |
          CHANGED_FILES=$(git diff --name-only origin/dev...HEAD)
          if echo "$CHANGED_FILES" | grep "^backend/"; then
            echo "Error: Changes in 'backend' folder are not allowed in 'frontend_dev'."
            exit 1
          else
            echo "No changes in the backend folder."
          fi

  merge:
    needs: [check-backend-changes, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: frontend_dev
        
      - name: Create PR to dev
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: frontend_dev
          branch: dev
          commit-message: Auto Pull Request
          title: "Sync frontend_dev into dev"
          body: "This PR was created automatically by GitHub Actions."
